export const QUIZ_QUESTIONS = [
  {
    id: 1,
    titleKey: "q1_title",
    options: [
      { textKey: "q1_opt1", icon: "💪" },
      { textKey: "q1_opt2", icon: "🦾" },
      { textKey: "q1_opt3", icon: "🍑" },
      { textKey: "q1_opt4", icon: "🏋️" },
    ],
  },
  {
    id: 2,
    titleKey: "q2_title",
    options: [
      { textKey: "q2_opt1", icon: "😞" },
      { textKey: "q2_opt2", icon: "💪" },
      { textKey: "q2_opt3", icon: "⚖️" },
      { textKey: "q2_opt4", icon: "🐢" },
    ],
  },
  {
    id: 3,
    titleKey: "q3_title",
    options: [
      { textKey: "q3_opt1", icon: "🆕" },
      { textKey: "q3_opt2", icon: "⏰" },
      { textKey: "q3_opt3", icon: "📅" },
      { textKey: "q3_opt4", icon: "🔄" },
    ],
  },
  {
    id: 4,
    titleKey: "q4_title",
    options: [
      { textKey: "q4_opt1", icon: "😐" },
      { textKey: "q4_opt2", icon: "🎲" },
      { textKey: "q4_opt3", icon: "🥗" },
      { textKey: "q4_opt4", icon: "📋" },
    ],
  },
  {
    id: 5,
    titleKey: "q5_title",
    options: [
      { textKey: "q5_opt1", icon: "0️⃣" },
      { textKey: "q5_opt2", icon: "1️⃣" },
      { textKey: "q5_opt3", icon: "3️⃣" },
      { textKey: "q5_opt4", icon: "5️⃣" },
    ],
  },
  {
    id: 6,
    titleKey: "q6_title",
    options: [
      { textKey: "q6_opt1", icon: "🎯" },
      { textKey: "q6_opt2", icon: "🗺️" },
      { textKey: "q6_opt3", icon: "⏳" },
      { textKey: "q6_opt4", icon: "📊" },
    ],
  },
  {
    id: 7,
    titleKey: "q7_title",
    options: [
      { textKey: "q7_opt1", icon: "🔥" },
      { textKey: "q7_opt2", icon: "🤔" },
      { textKey: "q7_opt3", icon: "❓" },
      { textKey: "q7_opt4", icon: "🚫" },
    ],
  },
]

export const QUIZ_MESSAGES = {
  en: {
    questionLabel: "Question",
    noScroll: "No scrolling needed - answer and move forward",
    startButton: "Start Quiz",
    opening: {
      title: "Want to discover why your muscles aren't growing?",
      subtitle: "Answer 7 quick questions and discover your Mass Gain Profile to truly change your body.",
    },
  },
  pt: {
    questionLabel: "Pergunta",
    noScroll: "Sem rolagem necessária - responda e avance",
    startButton: "Iniciar Quiz",
    opening: {
      title: "😳 Quer descobrir por que seus músculos não crescem?",
      subtitle: "Responda 7 perguntas rápidas e descubra seu Perfil de Ganho de Massa para mudar seu corpo de verdade.",
    },
  },
  es: {
    questionLabel: "Pregunta",
    noScroll: "Sin desplazamiento necesario - responde y avanza",
    startButton: "Comenzar Quiz",
    opening: {
      title: "¿Quieres descubrir por qué tus músculos no crecen?",
      subtitle:
        "Responde 7 preguntas rápidas y descubre tu Perfil de Ganancia de Masa para cambiar tu cuerpo de verdad.",
    },
  },
  fr: {
    questionLabel: "Question",
    noScroll: "Sans défilement — répondez et avancez",
    startButton: "Commencer le quiz",
    opening: {
      title: "Vous voulez savoir pourquoi vos muscles ne grandissent pas ?",
      subtitle: "Répondez à 7 questions rapides et découvrez votre Profil de Prise de Masse pour transformer votre corps.",
    },
  },
  hi: {
    questionLabel: "प्रश्न",
    noScroll: "स्क्रोल नहीं — उत्तर दें और आगे बढ़ें",
    startButton: "क्विज़ शुरू करें",
    opening: {
      title: "जानना चाहते हैं कि आपकी मसल्स क्यों नहीं बढ़ रहीं?",
      subtitle: "7 तेज़ सवालों के जवाब दें और अपना मास गेन प्रोफ़ाइल जानें — जिससे आपका शरीर सच में बदल सके।",
    },
  },
}

export const QUIZ_TRANSLATIONS = {
  en: {
    questions: {
      q1_title: "What is your biggest goal right now?",
      q2_title: "How do you feel about your body today?",
      q3_title: "How long have you been trying to change your body?",
      q4_title: "How is your nutrition?",
      q5_title: "How many times a week do you train?",
      q6_title: "What bothers you the most?",
      q7_title:
        "If you had a simple 30-day plan with quick workouts and a meal plan for real muscle gain... would you start today?",
    },
    options: {
      q1_opt1: "Increase mass all over my body",
      q1_opt2: "Get bigger arms and chest",
      q1_opt3: "Increase thighs and glutes",
      q1_opt4: "Define my abs without losing muscle",
      q2_opt1: "Very thin / No muscles",
      q2_opt2: "Strong, but without visible muscles",
      q2_opt3: "I gain weight easily, but it's just fat",
      q2_opt4: "I always take too long to gain mass",
      q3_opt1: "I just started",
      q3_opt2: "3+ months",
      q3_opt3: "1+ year!",
      q3_opt4: "I've quit and come back several times",
      q4_opt1: "I eat little and wrong",
      q4_opt2: "I eat a lot, but without quality",
      q4_opt3: "I try to eat proteins... sometimes I fail",
      q4_opt4: "I have a plan, but I don't follow it",
      q5_opt1: "I don't train yet",
      q5_opt2: "1-2x per week",
      q5_opt3: "3-4x per week",
      q5_opt4: "5+ times per week!",
      q6_opt1: "Lack of discipline",
      q6_opt2: "Lack of guidance",
      q6_opt3: "Lack of time",
      q6_opt4: "Not seeing results quickly",
      q7_opt1: "Yes! I want to change NOW 🔥",
      q7_opt2: "Maybe... convince me",
      q7_opt3: "I still don't know",
      q7_opt4: "No thanks",
    },
  },
  pt: {
    questions: {
      q1_title: "Qual é seu maior objetivo agora?",
      q2_title: "Como você se sente com seu corpo hoje?",
      q3_title: "Há quanto tempo você tenta mudar seu corpo?",
      q4_title: "Como você diria que é sua alimentação?",
      q5_title: "Quantas vezes você treina por semana?",
      q6_title: "O que mais te atrapalha a crescer?",
      q7_title:
        "Se você tivesse um plano simples de 30 dias com treinos rápidos e cardápio para ganho REAL de massa… você toparia começar ainda hoje?",
    },
    options: {
      q1_opt1: "Aumentar massa no corpo todo 💪",
      q1_opt2: "Ficar com braços e peito maiores",
      q1_opt3: "Aumentar coxas e glúteos 🍑",
      q1_opt4: "Definir a barriga sem perder músculos 🏋️‍♂️",
      q2_opt1: "Muito magro(a) / Sem músculos",
      q2_opt2: "Forte, mas sem músculos aparentes",
      q2_opt3: "Ganho peso fácil, mas é só gordura 😅",
      q2_opt4: "Sempre demoro demais pra ganhar massa",
      q3_opt1: "Comecei agora",
      q3_opt2: "+3 meses",
      q3_opt3: "+1 ano!",
      q3_opt4: "Já desisti e voltei várias vezes",
      q4_opt1: "Como pouco e errado",
      q4_opt2: "Como muito, mas sem qualidade 😬",
      q4_opt3: "Tento comer proteínas… às vezes falho",
      q4_opt4: "Tenho um plano, mas não sigo 😅",
      q5_opt1: "Não treino ainda",
      q5_opt2: "1–2x",
      q5_opt3: "3–4x",
      q5_opt4: "5+ vezes! 🔥",
      q6_opt1: "Falta de disciplina",
      q6_opt2: "Falta de orientação",
      q6_opt3: "Falta de tempo",
      q6_opt4: "Não ver resultado rápido",
      q7_opt1: "Sim! Quero mudar AGORA 🔥",
      q7_opt2: "Talvez… me convença",
      q7_opt3: "Ainda não sei",
      q7_opt4: "Não, obrigado",
    },
  },
  es: {
    questions: {
      q1_title: "¿Cuál es tu mayor objetivo ahora?",
      q2_title: "¿Cómo te sientes con tu cuerpo hoy?",
      q3_title: "¿Cuánto tiempo llevas intentando cambiar tu cuerpo?",
      q4_title: "¿Cómo diría que es tu nutrición?",
      q5_title: "¿Cuántas veces a la semana entrenas?",
      q6_title: "¿Qué te atrapalha más para crecer?",
      q7_title:
        "¿Si tuvieras un plan simple de 30 días con entrenamientos rápidos y menú para ganancia REAL de masa… comenzarías hoy?",
    },
    options: {
      q1_opt1: "Aumentar masa en todo mi cuerpo 💪",
      q1_opt2: "Brazos y pecho más grandes",
      q1_opt3: "Aumentar muslos y glúteos 🍑",
      q1_opt4: "Definir abdomen sin perder músculos 🏋️‍♂️",
      q2_opt1: "Muy delgado(a) / Sin músculos",
      q2_opt2: "Fuerte, pero sin músculos visibles",
      q2_opt3: "Gano peso fácil, pero es solo grasa 😅",
      q2_opt4: "Siempre tardo demasiado en ganar masa",
      q3_opt1: "Acabo de empezar",
      q3_opt2: "+3 meses",
      q3_opt3: "+1 año!",
      q3_opt4: "Ya he abandonado y vuelto varias veces",
      q4_opt1: "Como poco y mal",
      q4_opt2: "Como mucho, pero sin calidad 😬",
      q4_opt3: "Intento comer proteínas… a veces fallo",
      q4_opt4: "Tengo un plan, pero no lo sigo 😅",
      q5_opt1: "Aún no entreno",
      q5_opt2: "1–2x",
      q5_opt3: "3–4x",
      q5_opt4: "¡5+ veces! 🔥",
      q6_opt1: "Falta de disciplina",
      q6_opt2: "Falta de orientación",
      q6_opt3: "Falta de tiempo",
      q6_opt4: "No ver resultados rápidamente",
      q7_opt1: "¡Sí! Quiero cambiar AHORA 🔥",
      q7_opt2: "Talvez… me convenza",
      q7_opt3: "Aún no sé",
      q7_opt4: "No gracias",
    },
  },
  fr: {
    questions: {
      q1_title: "Quel est votre plus grand objectif en ce moment ?",
      q2_title: "Comment vous sentez-vous par rapport à votre corps aujourd'hui ?",
      q3_title: "Depuis combien de temps essayez-vous de changer votre corps ?",
      q4_title: "Comment décririez-vous votre alimentation ?",
      q5_title: "Combien de fois par semaine vous vous entraînez ?",
      q6_title: "Qu'est-ce qui vous gêne le plus pour progresser ?",
      q7_title:
        "Si vous aviez un plan simple de 30 jours avec des entraînements rapides et un menu pour une prise de masse RÉELLE… commenceriez-vous aujourd'hui ?",
    },
    options: {
      q1_opt1: "Augmenter la masse sur tout le corps 💪",
      q1_opt2: "Avoir des bras et un torse plus grands",
      q1_opt3: "Augmenter cuisses et fessiers 🍑",
      q1_opt4: "Définir les abdos sans perdre du muscle 🏋️‍♂️",
      q2_opt1: "Très maigre / Sans muscles",
      q2_opt2: "Fort, mais sans muscles visibles",
      q2_opt3: "Je prends du poids facilement, mais ce n'est que de la graisse 😅",
      q2_opt4: "Je mets toujours trop de temps à prendre de la masse",
      q3_opt1: "Je viens de commencer",
      q3_opt2: "+3 mois",
      q3_opt3: "+1 an !",
      q3_opt4: "J'ai abandonné et repris plusieurs fois",
      q4_opt1: "Je mange peu et mal",
      q4_opt2: "Je mange beaucoup, mais sans qualité 😬",
      q4_opt3: "J'essaie de manger des protéines… parfois j'échoue",
      q4_opt4: "J'ai un plan, mais je ne le suis pas 😅",
      q5_opt1: "Je ne m'entraîne pas encore",
      q5_opt2: "1–2x",
      q5_opt3: "3–4x",
      q5_opt4: "5+ fois ! 🔥",
      q6_opt1: "Manque de discipline",
      q6_opt2: "Manque d'orientation",
      q6_opt3: "Manque de temps",
      q6_opt4: "Ne pas voir des résultats rapidement",
      q7_opt1: "Oui ! Je veux changer MAINTENANT 🔥",
      q7_opt2: "Peut-être… convainquez-moi",
      q7_opt3: "Je ne sais pas encore",
      q7_opt4: "Non merci",
    },
  },
  hi: {
    questions: {
      q1_title: "अभी आपका सबसे बड़ा लक्ष्य क्या है?",
      q2_title: "आज अपने शरीर के बारे में आप कैसा महसूस करते हैं?",
      q3_title: "आप कब से अपना शरीर बदलने की कोशिश कर रहे हैं?",
      q4_title: "आप अपना खानपान कैसे बताएंगे?",
      q5_title: "आप सप्ताह में कितनी बार ट्रेनिंग करते हैं?",
      q6_title: "विकास में आपको सबसे ज़्यादा क्या रोकता है?",
      q7_title:
        "अगर आपके पास 30 दिनों का सरल प्लान हो, तेज़ वर्कआउट्स और असली मास गेन के लिए डाइट… तो क्या आप आज से शुरू करेंगे?",
    },
    options: {
      q1_opt1: "पूरे शरीर में मास बढ़ाना 💪",
      q1_opt2: "बड़े बाजू और छाती पाना",
      q1_opt3: "जांघ और ग्लूट्स बढ़ाना 🍑",
      q1_opt4: "एब्स को परिभाषित करना, मसल्स खोए बिना 🏋️‍♂️",
      q2_opt1: "बहुत दुबला / बिना मसल्स",
      q2_opt2: "मजबूत, लेकिन दिखने वाले मसल्स नहीं",
      q2_opt3: "वजन जल्दी बढ़ता है, पर सिर्फ़ चर्बी 😅",
      q2_opt4: "मुझे मास बढ़ाने में हमेशा बहुत समय लगता है",
      q3_opt1: "मैं अभी शुरू किया है",
      q3_opt2: "+3 महीने",
      q3_opt3: "+1 साल!",
      q3_opt4: "कई बार छोड़ा और फिर शुरू किया",
      q4_opt1: "कम और गलत खाना",
      q4_opt2: "ज़्यादा खाना, पर गुणवत्ता नहीं 😬",
      q4_opt3: "प्रोटीन खाने की कोशिश… कभी-कभी विफल",
      q4_opt4: "प्लान है, लेकिन पालन नहीं करता 😅",
      q5_opt1: "अभी ट्रेनिंग नहीं करता",
      q5_opt2: "1–2x",
      q5_opt3: "3–4x",
      q5_opt4: "5+ बार! 🔥",
      q6_opt1: "अनुशासन की कमी",
      q6_opt2: "मार्गदर्शन की कमी",
      q6_opt3: "समय की कमी",
      q6_opt4: "तेज़ नतीजे न दिखना",
      q7_opt1: "हाँ! मैं अभी बदलना चाहता हूँ 🔥",
      q7_opt2: "शायद… मुझे मनाइए",
      q7_opt3: "अभी नहीं पता",
      q7_opt4: "नहीं, धन्यवाद",
    },
  },
}
